name = "demo-push-notifier"
compatibility_date = "2024-04-13"
main = "worker.js"

[[d1_databases]]
binding = "DB"
database_name = "demo-push"
database_id = "e01bd4ea-4dc1-4de3-8fb0-cb0a84643a6f"
preview_database_id = "DB"

[triggers]
crons = [ "*/3 * * * *" ]

[vars]
PUSH_SERVER_PUBLIC_KEY = "BCUdAv5I5pJwseflX848zH2IQHwaSsvMRcE-7Exhq-ES1HssHg_UnHeinOlN9rg3dLrdSPd0IFfMvK08Ixj8e0w"
